spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customer-service/**
server:
  port: 8071
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
       defaultZone: http://localhost:8761/eureka      