spring:
  application:
    name: eurekaserver 
  config:
    import: optional:configserver:http://localhost:8000   
eureka:
  client:
    register-with-eureka: false
    fatch-registry: false
server:
  port: 8761

    
